# Stage 1: Build the application using Maven
FROM maven:3.8-openjdk-17 AS build

# Set the working directory
WORKDIR /app

# Copy the pom.xml file to download dependencies
COPY pom.xml .

# Download all dependencies from pom.xml
RUN mvn dependency:go-offline

# Copy the rest of the application source code
COPY src ./src

# Package the application, skipping tests
RUN mvn clean package -DskipTests

# Stage 2: Create the final image with Tomcat
FROM tomcat:9.0-jdk17-temurin

# Remove the default ROOT application
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy the .war file from the build stage to Tomcat's webapps directory
# The artifact name is based on what's typically generated by Spring Boot/Maven.
# Please adjust 'tutorhub-be-0.0.1-SNAPSHOT.war' if your artifactId or version is different.
COPY --from=build /app/target/tutorhub-be-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

# Expose port 8080
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]

